repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.245
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: "3.0.5"
    hooks:
      - id: sqlfluff-lint
        additional_dependencies:
          ["dbt-duckdb==1.7.4", "sqlfluff-templater-dbt==3.0.5"]
      - id: sqlfluff-fix
        additional_dependencies:
          ["dbt-duckdb==1.7.4", "sqlfluff-templater-dbt==3.0.5"]
  - repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
      - id: black
